### ISSUE TITLE
access carema directly

### ISSUE THREAD

**Issue by imir-hoxha** [KoenZomers/RingApi#15]
the api accesses the data on cloud and not directly being connected with the camera. How can I connect to the camera directly as I would like to save my data in my own cloud account or on one of my computers? 
By the way, I used the API and authenticated successfully but then I got forbidden. (403)
Probably this has to do with the fact that I don't have a plus subscription (no cloud account). but still it should not throw a "Forbidden".

**Comment by KoenZomers** [comment]
As far as I know it is not possible to connect to the camera directly. Ring has blocked this off and the Ring devices push their data to their cloud instead of you being able to pull it from the device itself.

I only have one Ring doorbell and it does have the subscription, so unfortunately I can't test how this all works or doesn't work for devices without this subscription.

**Comment by KoenZomers** [comment]
Closing as no further feedback received
